export const HIDE_ADD_MESSAGE = 'HIDE_ADD_MESSAGE';
export const SHOW_ADD_MESSAGE = 'SHOW_ADD_MESSAGE';

// search
export const START_SEARCH = 'START_SEARCH';
export const BUSY_SEARCHING = 'BUSY_SEARCHING';
export const SET_SEARCH_STRING = 'SET_SEARCH_STRING';
export const SAVE_SEARCH_RESULT_ID = 'SAVE_SEARCH_RESULT_ID';
export const RECEIVE_SEARCH_RESULT = 'RECEIVE_SEARCH_RESULT';
export const CLEAR_SEARCH_STRING = 'CLEAR_SEARCH_STRING';

// tiles and tags
export const TAG_ADD_SINGLE_TAG = 'TAG_ADD_SINGLE_TAG';
export const TAG_ADD_TAGS = 'TAG_ADD_TAGS';
export const TAG_REMOVE_TAG = 'TAG_REMOVE_TAG';
export const TILES_ADD_TILES = 'TILES_ADD_TILES';
export const UPDATE_DISPLAYED_ITEMS = 'UPDATE_DISPLAYED_ITEMS';
export const REMOVE_TAG = 'REMOVE_TAG';
export const FILTER_ON_CLICK = 'FILTER_ON_CLICK';

// autocomplete
export const SET_AUTOCOMPLETE_OPTIONS = 'SET_AUTOCOMPLETE_OPTIONS';
export const SET_AUTOCOMPLETE_ERROR = 'SET_AUTOCOMPLETE_ERROR';
export const SET_AUTOCOMPLETE_IN_SEARCH = 'SET_AUTOCOMPLETE_IN_SEARCH';

// errors
export const SEARCH_ERROR = 'SEARCH_ERROR';
