export const HIDE_ADD_MESSAGE = 'HIDE_ADD_MESSAGE';
export const SHOW_ADD_MESSAGE = 'SHOW_ADD_MESSAGE';
export const REMOVE_TAG = 'REMOVE_TAG';
export const FILTER_ON_CLICK = 'FILTER_ON_CLICK';
export const QUERY_FETCH_SEARCH_RESULTS = 'QUERY_FETCH_SEARCH_RESULTS';
export const RECEIVE_SEARCH_RESULT = 'RECEIVE_SEARCH_RESULT';
export const START_SEARCH = 'START_SEARCH';
export const BUSY_SEARCHING = 'BUSY_SEARCHING';

export const TAG_ADD_SINGLE_TAG = 'TAG_ADD_SINGLE_TAG';
export const TAG_ADD_TAGS = 'TAG_ADD_TAGS';
export const TAG_REMOVE_TAG = 'TAG_REMOVE_TAG';
export const TILES_ADD_TILES = 'TILES_ADD_TILES';
export const SET_SEARCH_STRING = 'SET_SEARCH_STRING';
export const SAVE_SEARCH_RESULT_ID = 'SAVE_SEARCH_RESULT_ID';
