export const HIDE_ADD_MESSAGE = 'HIDE_ADD_MESSAGE';
export const SHOW_ADD_MESSAGE = 'SHOW_ADD_MESSAGE';

// search
export const START_SEARCH = 'START_SEARCH';
export const BUSY_SEARCHING = 'BUSY_SEARCHING';
export const SET_SEARCH_STRING = 'SET_SEARCH_STRING';
export const SAVE_SEARCH_RESULT_ID = 'SAVE_SEARCH_RESULT_ID';
export const SAVE_BUCKET_ID = 'SAVE_BUCKET_ID';
export const RECEIVE_SEARCH_RESULT = 'RECEIVE_SEARCH_RESULT';
export const CLEAR_SEARCH_STRING = 'CLEAR_SEARCH_STRING';

// tiles and tags
export const TAG_ADD_SINGLE_TAG = 'TAG_ADD_SINGLE_TAG';
export const TAG_ADD_TAGS = 'TAG_ADD_TAGS';
export const TAG_REMOVE_TAG = 'TAG_REMOVE_TAG';
export const TILES_ADD_TILES = 'TILES_ADD_TILES';
export const REMOVE_TAG = 'REMOVE_TAG';
export const FILTER_ON_CLICK = 'FILTER_ON_CLICK';

// autocomplete
export const SET_AUTOCOMPLETE_OPTIONS = 'SET_AUTOCOMPLETE_OPTIONS';
export const SET_AUTOCOMPLETE_ERROR = 'SET_AUTOCOMPLETE_ERROR';
export const SET_AUTOCOMPLETE_IN_SEARCH = 'SET_AUTOCOMPLETE_IN_SEARCH';

// errors
export const SEARCH_ERROR = 'SEARCH_ERROR';

// temp routing
export const VIEW_ARTICLE = 'VIEW_ARTICLE';

// hotel page
export const SET_HOTEL_PAGE = 'SET_HOTEL_PAGE';

// travel info
export const SET_CHILD_AGE = 'SET_CHILD_AGE';
export const SET_NUMBER_OF_ADULTS = 'SET_NUMBER_OF_ADULTS';
export const SET_NUMBER_OF_CHILDREN = 'SET_NUMBER_OF_CHILDREN';
export const SET_DEPARTURE_DATE = 'SET_DEPARTURE_DATE';
export const SET_DEPARTURE_AIRPORT = 'SET_DEPARTURE_AIRPORT';
export const SET_DURATION = 'SET_DURATION';
export const SET_PASSENGER_BIRTHDAYS = 'SET_PASSENGER_BIRTHDAYS';
export const UPDATE_HEADER_TITLES = 'UPDATE_HEADER_TITLES';

// web sockets
export const SAVE_SOCKET_CONNECTION_ID = 'SAVE_SOCKET_CONNECTION_ID';

// fingerprint
export const SET_FINGERPRINT = 'SET_FINGERPRINT';
